spring.application.name=dashboard2026-BE
spring.datasource.url=jdbc:postgresql://localhost:5432/dashboard
spring.datasource.username=postgres
spring.datasource.password=Ivanytskyi
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
